using System.Collections;
using System.Collections.Generic;
using UnityEngine;
using UnityEngine.UI;
using System;


public class GradeScript : MonoBehaviour
{
    //WW
    public InputField WRITTENWORKMYSCOREINPUT;
    public InputField WRITTENWORKTOTALSCOREINPUT;
    public float WRITTENWORKMYSCORE;
    public float WRITTENWORKTOTALSCORE;
    public float  WRITTENWORKPERCENTAGE;
    public float WRITTENWORKWEIGHTEDPERCENTAGE;
    //PT
    public InputField PERFORMANCETASKMYSCOREINPUT;
    public InputField PERFORMANCETASKTOTALSCOREINPUT;
    public float PERFORMANCETASKMYSCORE;
    public float PERFORMANCETASKTOTALSCORE;
    public float PERFORMANCETASKPERCENTAGE;
    public float PERFORMANCETASKWEIGHTEDPERCENTAGE;
    
    //QA
    public InputField QUARTERLYASSESSMENTMYSCOREINPUT;
    public InputField QUARTERLYASSESSMENTTOTALSCOREINPUT;
    public float QUARTERLYASSESSMENTMYSCORE;
    public float QUARTERLYASSESSMENTTOTALSCORE;
    public float QUARTERLYASSESSMENTPERCENTAGE;
    public float QUARTERLYASSESSMENTWEIGHTEDPERCENTAGE;

    //Final grade
    public double TOTALOVERALLGRADE;
    public Text result_text;

    public void Grade()
    {
        float.TryParse(WRITTENWORKMYSCOREINPUT.text, out float WRITTENWORKPARSEMYSCOREINPUT );
        float.TryParse(PERFORMANCETASKMYSCOREINPUT.text, out float PERFORMANCETASKPARSEMYSCOREINPUT);
        float.TryParse(QUARTERLYASSESSMENTMYSCOREINPUT.text, out float QUARTERLYASSESSMENTPARSEMYSCOREINPUT);
        float.TryParse(WRITTENWORKTOTALSCOREINPUT.text, out float WRITTENWORKPARSETOTALSCOREINPUT);
        float.TryParse(PERFORMANCETASKTOTALSCOREINPUT.text, out float PERFORMANCETASKPARSETOTALSCOREINPUT);
        float.TryParse(QUARTERLYASSESSMENTTOTALSCOREINPUT.text, out float QUARTERLYASSESSMENTPARSETOTALSCOREINPUT); 

        WRITTENWORKMYSCORE = WRITTENWORKPARSEMYSCOREINPUT;
        WRITTENWORKTOTALSCORE = WRITTENWORKPARSETOTALSCOREINPUT;
        PERFORMANCETASKMYSCORE = PERFORMANCETASKPARSEMYSCOREINPUT;
        PERFORMANCETASKTOTALSCORE = PERFORMANCETASKPARSETOTALSCOREINPUT;
        QUARTERLYASSESSMENTMYSCORE = QUARTERLYASSESSMENTPARSEMYSCOREINPUT;
        QUARTERLYASSESSMENTTOTALSCORE = QUARTERLYASSESSMENTPARSETOTALSCOREINPUT;

        WRITTENWORKPERCENTAGE = (WRITTENWORKMYSCORE/ WRITTENWORKTOTALSCORE)*100;
        PERFORMANCETASKPERCENTAGE = (PERFORMANCETASKMYSCORE / PERFORMANCETASKTOTALSCORE)*100;
        QUARTERLYASSESSMENTPERCENTAGE = (QUARTERLYASSESSMENTMYSCORE / QUARTERLYASSESSMENTTOTALSCORE) * 100;


        WRITTENWORKWEIGHTEDPERCENTAGE = WRITTENWORKPERCENTAGE * 0.2f;
        PERFORMANCETASKWEIGHTEDPERCENTAGE = PERFORMANCETASKPERCENTAGE * 0.6f;
        QUARTERLYASSESSMENTWEIGHTEDPERCENTAGE = QUARTERLYASSESSMENTPERCENTAGE * 0.2f;


        TOTALOVERALLGRADE = Math.Round((double)(WRITTENWORKWEIGHTEDPERCENTAGE + PERFORMANCETASKWEIGHTEDPERCENTAGE + QUARTERLYASSESSMENTWEIGHTEDPERCENTAGE), 2);

        result_text.text = "Final Grade: " + TOTALOVERALLGRADE.ToString() + "%";

    }
}
